// Code generated by "stringer -type=Player"; DO NOT EDIT.

package tictactoe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayerA-0]
	_ = x[PlayerB-1]
}

const _Player_name = "PlayerAPlayerB"

var _Player_index = [...]uint8{0, 7, 14}

func (i Player) String() string {
	if i < 0 || i >= Player(len(_Player_index)-1) {
		return "Player(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Player_name[_Player_index[i]:_Player_index[i+1]]
}
